apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name nginxtl.local;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }

            location = /favicon.ico {
                log_not_found off;
                access_log off;
            }

            location = /robots.txt {
                log_not_found off;
                access_log off;
            }

            access_log off;

            sendfile off;

            client_max_body_size 100m;

            location ~ /\.ht {
                deny all;
            }
        }
    }
